File writer - interval
OceanDataTools/openrvdas pull request #292
Opened 2021-11-02 11:34 UTC by webbpinner

Adds ability to truncate files every x hours or x minutes.  Before committing please ponder any negative performance impacts cause by the more complex processing of the file name... this is working for my test case but may be a problem for higher data rate streams.

2021-11-03 14:26 UTC, davidpablocohn requested changes
Can be more efficient with the interval checking by maintaining a "next_file_split" time variable - see inline.

2021-11-03 14:26 UTC, davidpablocohn commented on logger/writers/file_writer.py
> +        split_interval Splits files based on a defined hour or minute time
Expand text a little to make it clear that suffix must be either 'H' or 'M'

2021-11-03 14:26 UTC, davidpablocohn commented on logger/writers/file_writer.py
> +        if split_interval is None:
Get rid of conditional, and have
```
self.split_interval = None
self.next_file_split = 0
```
We want self.split_interval to be defined, regardless.

Then see below for checking whether it's time to roll over to a new file.

2021-11-03 14:26 UTC, davidpablocohn commented on logger/writers/file_writer.py
> +        else:
Break the parsing of the interval off into its own little method, for clarity.  Maybe _split_interval_in_seconds()?

2021-11-03 14:26 UTC, davidpablocohn commented on logger/writers/file_writer.py
> +        if self.split_by_time or self.split_interval is not None:
More efficient - if splitting by interval, we only call _get_new_file_suffix() when the right amount of time has passed.
```
    if self.split_by_time or (self.split_interval and time.now() > self.next_file_split):
      if self.split_interval:  # if we're splitting by interval, set time for our next split
        self.next_file_split = self.next_file_split + self.split_interval 
    new_file_suffix = ...  # rest of clause
        
```

2021-11-03 15:48 UTC, webbpinner commented on logger/writers/file_writer.py
> +        if self.split_by_time or self.split_interval is not None:
This is what I couldn't think of but figured was possible.  Makes much more sense.

2021-11-03 16:06 UTC, davidpablocohn commented
Yeah, that's why I get the big bucks... :)

BTW: this PR makes me finally understand the request from SailDrone in the
survey about "different logging intervals." Seems like a fine idea - thanks
for implementing it!

On Wed, Nov 3, 2021 at 8:48 AM Webb Pinner ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In logger/writers/file_writer.py
> <https://github.com/OceanDataTools/openrvdas/pull/292#discussion_r742080918>
> :
>
> > @@ -120,7 +190,7 @@ def write(self, record):
>
>          # If we're splitting by some time interval, see if it's time to
>          # roll over to a new file.
> -        if self.split_by_time:
> +        if self.split_by_time or self.split_interval is not None:
>
> This is what I couldn't think of but figured was possible. Makes much more
> sense.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OceanDataTools/openrvdas/pull/292#discussion_r742080918>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFO7V3TJBWKCKUMUJTJYII3UKFRU5ANCNFSM5HGHMV3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-09 14:23 UTC, webbpinner commented
Made changes based on recommendations.  These are untested but I wanted to make sure I was moving in the right direction.

2021-11-09 17:53 UTC, davidpablocohn approved these changes
Yup - this looks good.

2021-11-09 17:55 UTC, webbpinner commented
ok... I'll actually test the code this next round and will report back.

2021-11-09 17:56 UTC, davidpablocohn commented
Sounds good - thanks!

On Tue, Nov 9, 2021 at 9:55 AM Webb Pinner ***@***.***> wrote:

> ok... I'll actually test the code this next round and will report back.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OceanDataTools/openrvdas/pull/292#issuecomment-964394076>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFO7V3RYUAKYE4JY75SAQV3ULFOCRANCNFSM5HGHMV3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-09 23:23 UTC, davidpablocohn approved these changes

2021-11-10 14:19 UTC, merged