For upstream/tcpwriter
OceanDataTools/openrvdas pull request #348
Opened 2023-10-24 02:59 UTC by veggiemike

Pablo, this branch should do exactly what we discussed for Issue #347.  The first couple commits are almost identical to changes made to UDPWriter last week, then it removes UDP from NetworkWriter, gets TCP working, renames it to TCPWriter, and leaves behind a noisy NetworkWriter class that just tells users to use UDPWriter or TCPWriter.
I've also added `--write_tcp` to `listen.py` and fixed encoding usage in there so it can use UDPWriter and TCPWriter with raw/binary data (should have done that previously, but didn't realize it existed).
Thanks!

2023-10-24 20:50 UTC, davidpablocohn requested changes

2023-10-24 20:50 UTC, davidpablocohn commented on logger/listener/listen.py
>      parser.add_argument('--write_network', dest='write_network', default=None,
Wondering if it makes sense to remove --write_network...

2023-10-24 20:50 UTC, davidpablocohn commented on logger/listener/listen.py
> +                        '[destination]:port[,...]')
I think you want this to be [destination:]port rather than [destination]:port? (That is, with the colon optional)

2023-10-24 20:50 UTC, davidpablocohn commented on logger/listener/listen.py
> +    parser.add_argument('--encoding', dest='encoding', default='utf-8',
Excellent.

2023-10-24 20:50 UTC, davidpablocohn commented on logger/listener/listen.py
> +                                     'should be [source]:port[,...]')
Again - shouldn't the colon be inside the square brackets? I think we risk breaking existing scripts out there if we make it obligatory when just specifying port.

2023-10-24 20:50 UTC, davidpablocohn commented on logger/listener/listen.py
>                      addr = addr_str.split(':')
It does look like you're requiring the colon for --write_udp. I'd rather not do that, as it could break existing scripts. But let me know if I'm missing something about this?

2023-10-24 20:50 UTC, davidpablocohn commented on logger/writers/udp_writer.py
> +        # socket get's initialized on-demand in write()
s/get's/gets/

2023-10-24 20:50 UTC, davidpablocohn commented on logger/writers/tcp_writer.py
> +        port         Port to which packets should be sent
Puzzled that the order is port, destination rather than destination, port - I'm used to thinking of addresses as destination:port...

2023-10-24 20:50 UTC, davidpablocohn commented on logger/writers/tcp_writer.py
> +        self.port = int(port)
Wondering if we should have an explicit error message for this rather than having it just throw the exception if port isn't an int.

2023-10-24 21:36 UTC, veggiemike commented on logger/listener/listen.py
>      parser.add_argument('--write_network', dest='write_network', default=None,
Could certainly remove it.  Users will get an invalid usage message instead of errors telling them to use UDPWriter or TCPWriter.  But that feels less critical than a configured .yml file blowing up because NetworkWriter isn't defined.  In fact, it almost feels more appropriate for a cli tool to just give you a usage error.
Shall I remove it?

2023-10-24 21:45 UTC, veggiemike commented on logger/writers/tcp_writer.py
> +        port         Port to which packets should be sent
Yeah, I don't like it either.  I was trying to match UDPWriter, which does it that way because `destination` is an optional parameter there.  I'll swap them in TCPWriter to "feel right" and shrug that that's just the way it works in UDPWriter.

2023-10-24 21:51 UTC, veggiemike commented on logger/listener/listen.py
>                      addr = addr_str.split(':')
I made the colon required for 2 reasons:  1) argument parsing is simpler, and 2) I've always seen the colon as required in other applications.  Semantically, you specify an "address" as :8000 and a port as 8000.  That being said, you're right about it breaking existing scripts...  Shall I gin up a patch to make the colon optional and fix the help messages to match?

2023-10-24 21:51 UTC, veggiemike commented on logger/writers/udp_writer.py
> +        # socket get's initialized on-demand in write()
Ha, will fix

2023-10-24 22:05 UTC, veggiemike commented on logger/writers/tcp_writer.py
> +        self.port = int(port)
I honestly don't really feel an error/warning message is needed here.  Pretty sure I did the exact same thing in UDPWriter (silently made it an int).  Just a Python types-dont-matter-ism, if you will.  I can certainly add a warning message to both TCPWriter and UDPWriter for that, if you'd like.

2023-10-25 15:01 UTC, davidpablocohn commented on logger/listener/listen.py
>      parser.add_argument('--write_network', dest='write_network', default=None,
Right - good point. Hmmm, waffling. Let's go just leave it in for now, and plan to excise it completely later.

2023-10-25 15:09 UTC, davidpablocohn commented on logger/listener/listen.py
>                      addr = addr_str.split(':')
Yes, please - thanks! You're right about the semantics of "port" vs "address," of course. But I think the non-colon usage is sufficiently intuitive (and kind of hardwired into my fingers by now) that I'd like to keep it. Many thanks again.

2023-10-25 15:10 UTC, davidpablocohn commented on logger/writers/tcp_writer.py
> +        port         Port to which packets should be sent
Yeah - thanks! And future generations will curse us for our inconsistency. :)

2023-10-25 15:14 UTC, davidpablocohn commented on logger/listener/listen.py
>      parser.add_argument('--write_network', dest='write_network', default=None,
Ach - let's go ahead and leave it for now. It'll provide additional "didn't this used to work?" diagnostics for anyone who is actually using it. Then at some point I can snip it. Thanks!

2023-10-25 19:15 UTC, veggiemike commented on logger/listener/listen.py
>      parser.add_argument('--write_network', dest='write_network', default=None,
You got it!

2023-10-25 19:22 UTC, davidpablocohn commented
Oh - maybe on the "help" we could have a note saying "DEPRECATED in favor
of --udp and --tcp"?

On Wed, Oct 25, 2023 at 12:16 PM Michael D Labriola <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In logger/listener/listen.py
> <https://github.com/OceanDataTools/openrvdas/pull/348#discussion_r1372220682>
> :
>
> > @@ -483,9 +486,13 @@ def __init__(self, config_file, config_name=None, log_level=None):
>      parser.add_argument('--write_network', dest='write_network', default=None,
>
> You got it!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OceanDataTools/openrvdas/pull/348#discussion_r1372220682>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFO7V3QENTUCLGGPO2GYL7LYBFQPFAVCNFSM6AAAAAA6NAEE3WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOJYGA4DQNJZGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-10-25 19:27 UTC, veggiemike commented
Actually, we've more than deprecated it... it's gone.  But I'll stick something in the help message to say it's been REPLACED by `--write_udp` and `--write_tcp`.  So you get a notice in `--help` output, and if you try and run it, you get error messages that it's been replaced by UDPWriter and TCPWriter.  Should not go unnoticed, for sure.  Heh.

2023-10-25 19:29 UTC, davidpablocohn commented
Ah you're right! "Deprecated with Extreme Prejudice," then. :-)

On Wed, Oct 25, 2023, 9:28 AM Michael D Labriola ***@***.***>
wrote:

> Actually, we've more than deprecated it... it's gone. But I'll stick
> something in the help message to say it's been REPLACED by --write_udp
> and --write_tcp. So you get a notice in --help output, and if you try and
> run it, you get error messages that it's been replaced by UDPWriter and
> TCPWriter. Should not go unnoticed, for sure. Heh.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OceanDataTools/openrvdas/pull/348#issuecomment-1779918793>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFO7V3QRFRLRKME5ZMZT2SDYBFR4JAVCNFSM6AAAAAA6NAEE3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZZHEYTQNZZGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-10-25 21:06 UTC, veggiemike commented
I think I've resolved all your comments, Pablo!

2023-10-25 21:09 UTC, davidpablocohn approved these changes

2023-10-25 21:10 UTC, merged

2023-10-25 21:10 UTC, davidpablocohn commented
Many thanks!