Make FileWriter support raw/binary output and other fixes
OceanDataTools/openrvdas pull request #350
Opened 2023-10-25 21:45 UTC by veggiemike

Hey, Pablo!  Here's a batch of fixes I made while making FileWriter work with raw/binary output.

2023-10-26 16:20 UTC, davidpablocohn requested changes

2023-10-26 16:20 UTC, davidpablocohn commented on logger/readers/reader.py
> +        if encoding == '':
Oops - thanks!

2023-10-26 16:20 UTC, davidpablocohn commented on logger/writers/file_writer.py
> +                     daily, but named via Julian date.  Putting '-' or '.' on
This is a great idea. At risk of getting too verbose, it may be worth adding that if the time format both ends *and* starts with '-' (or '.'), it will be used as a prefix. Actually thinking about it, filenames that start with a dash are problematic in Linux; would you mind flipping the code so that if it both starts and ends with a dash (or '.') it becomes a suffix?

2023-10-26 16:20 UTC, davidpablocohn commented on logger/writers/file_writer.py
> +                    # make it a prefix even though we've called it a suffix
See note above about behavior when 'suffix' both starts and ends with a '-'/'.'; I *think* the more benign behavior would be to have it be used as a suffix rather than prefix, but am willing to be convinced.

2023-10-26 19:44 UTC, veggiemike commented on logger/writers/file_writer.py
> +                    # make it a prefix even though we've called it a suffix
No convincing needed, that would indeed be the less ugly result.  I'll make it work that way

2023-10-27 13:56 UTC, davidpablocohn approved these changes

2023-10-27 13:57 UTC, merged