new functionality for nmea transform
OceanDataTools/openrvdas pull request #364
Opened 2024-03-07 03:14 UTC by ellapiet

add choice for which nmeas to use, add dpt and stn nmeas, add test

2024-03-07 05:25 UTC, davidpablocohn requested changes
I've not gone into depth on the the new transforms themselves, but in general they look reasonable. Only change I'd like would be some guardrails if the user specifies a transform that doesn't exist, so they can pinpoint what's wrong with their config.

Thanks!

2024-03-07 05:25 UTC, davidpablocohn commented on logger/transforms/nmea_transform.py
> +            class_const = getattr(module, transform)
Sanity checking here - can we fail more gently if user specifies a transform that isn't defined? I'm guessing it's too messy to procedurally emit a message that says what the allowable transforms are, but perhaps we could refer them to the code?

2024-03-14 04:38 UTC, ellapiet commented on logger/transforms/nmea_transform.py
> +            class_const = getattr(module, transform)
Done! Added check to compare provided transforms with all classes from the nmea_transforms file

2024-03-14 04:40 UTC, ellapiet commented on logger/transforms/nmea_transform.py
`import inspect`

2024-03-14 14:14 UTC, davidpablocohn approved these changes

2024-03-14 14:14 UTC, merged